In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
cd '/content/drive/MyDrive/Colab Notebooks/CS 520'

/content/drive/MyDrive/Colab Notebooks/CS 520

In [8]:
ls

adult.csv  Assignment1.ipynb  Untitled0.ipynb

In [10]:
import pandas

In [34]:
cols = [['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status',
           'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss',
           'hours-per-week', 'native-country', 'income']]
df = pandas.read_csv('adult.csv')
df = df.rename(columns = {'39':'age', 'State-gov':'workclass', '77516':'fnlwgt', 'Bachelors':'education',
                     '13':'education-num', 'Never-married':'marital-status', 'Adm-clerical':'occupation',
                     'Not-in-family':'relationship', 'White':'race', 'Male':'sex', '2174':'capital-gain',
                     '0':'capital-loss', '40':'hours-per-week', 'United-States':'native-country', '<=50K':'income'})

Printing number of rows and columns

In [ ]:
df.shape

Rows 1000-1010

In [ ]:
df.iloc[1000:1011]

Categorical Data Unique Values and Frequency

In [100]:
df['workclass'].value_counts()

Private             22696
Self-emp-not-inc     2541
Local-gov            2093
?                    1836
State-gov            1297
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: workclass, dtype: int64

In [63]:
df['education'].value_counts()

HS-grad         10501
Some-college     7291
Bachelors        5354
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           333
1st-4th           168
Preschool          51
Name: education, dtype: int64

In [ ]:
df['marital-status'].value_counts()

In [ ]:
df['occupation'].value_counts()

In [ ]:
df['relationship'].value_counts()

In [ ]:
df['race'].value_counts()

In [ ]:
df['sex'].value_counts()

In [ ]:
df['native-country'].value_counts()

In [71]:
df['income'].value_counts()

<=50K    24719
>50K      7841
Name: income, dtype: int64

Numerical Data Info

In [ ]:
df['age'].describe()

In [ ]:
df['education-num'].describe()

In [ ]:
df['capital-gain'].describe()

In [ ]:
df['capital-loss'].describe()

In [ ]:
df['hours-per-week'].describe()

Age < 20, income > 50k

In [ ]:
df[(df['age'] < 20) & (df['income'] == '>50K')]

Age 39-42, hours per week = 40

In [ ]:
df[(df['age'] <= 42) & (df['age'] >= 39) & (df['hours-per-week'] == 40)]

Capital Gain x Income

In [ ]:
#import matplotlib
df.plot(kind='scatter', x='capital-gain', y='income', title='Capital Gain x Income')

Subset

In [64]:
df2 = df[['age', 'education', 'sex', 'hours-per-week', 'income']]
df2 = df2[(df['education'] == 'Masters') | (df['education'] == 'Prof-school') |(df['education'] == 'Doctorate')]

In [ ]:
df2.head()

In [70]:
df2.tail()

       age    education     sex  hours-per-week income
32538   71    Doctorate    Male              10   >50K
32543   31      Masters  Female              30  <=50K
32547   65  Prof-school    Male              60  <=50K
32552   32      Masters    Male              11  <=50K
32553   53      Masters    Male              40   >50K

Age x Income Comparison

In [75]:
under50 = df[(df['income'] == '<=50K')]
over50 = df[(df['income'] == '>50K')]

In [ ]:
under50.describe()

In [ ]:
over50.describe()

The data shows that the average age of people who make under \$50K is 8 years younger than the average age of those who make over \$50K (36 and 44, respectively).

Histograms Comparing Hours Per Week and Income

In [ ]:
under50.plot(kind='hist', x='income', y='hours-per-week', title="<=50K Hours Per Week")

In [ ]:
over50.plot(kind='hist', x='income', y='hours-per-week', title="<=50K Hours Per Week")

Analysis of the histograms reveals that people who make greater than \$50k generally work longer hours than people who make under \$50K. There is a significant spike in frequency among the 40-70 hours per week chart in the greater than \$50k hours per week chart that is not present in the less than \$50k hours per week chart.

Subset (Over 50K)

In [105]:
over50sub = df[(df['age'] > 40) & (df['hours-per-week'] > 45) & ((df['education'] == 'Masters') | (df['education'] == 'Doctorate')) & (df['workclass'] == 'Federal-gov') & (df['fnlwgt'] !=74680) & (df['fnlwgt'] !=111700)]
over50sub

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
88,43,Federal-gov,410867,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,50,United-States,>50K
2323,63,Federal-gov,97855,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,>50K
2528,49,Federal-gov,213668,Masters,14,Never-married,Exec-managerial,Not-in-family,White,Male,0,0,56,United-States,>50K
2782,43,Federal-gov,186916,Masters,14,Divorced,Protective-serv,Not-in-family,White,Male,0,0,60,United-States,>50K
4353,53,Federal-gov,199720,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,15024,0,60,Germany,>50K
4804,51,Federal-gov,282680,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Female,0,1564,70,United-States,>50K
6119,48,Federal-gov,205707,Masters,14,Married-spouse-absent,Exec-managerial,Not-in-family,White,Female,10520,0,50,United-States,>50K
6452,42,Federal-gov,170230,Masters,14,Never-married,Exec-managerial,Not-in-family,White,Female,14084,0,60,United-States,>50K
6636,46,Federal-gov,43206,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Female,0,1564,50,United-States,>50K
10285,51,Federal-gov,73670,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,4386,0,52,United-States,>50K
11326,45,Federal-gov,171335,Masters,14,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,>50K
12703,41,Federal-gov,214838,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K
13482,55,Federal-gov,88876,Masters,14,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,60,United-States,>50K
17253,63,Federal-gov,39181,Doctorate,16,Divorced,Exec-managerial,Not-in-family,White,Female,0,2559,60,United-States,>50K
20392,55,Federal-gov,35723,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K
23598,51,Federal-gov,254211,Masters,14,Widowed,Sales,Unmarried,White,Male,0,0,50,El-Salvador,>50K

Subset (Under 50K)

In [111]:
under50sub = df[(df['age'] < 25) & (df['hours-per-week'] < 5)]
under50sub

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
2443,19,Private,171306,HS-grad,9,Never-married,Sales,Own-child,White,Male,0,0,3,United-States,<=50K
4567,18,Private,301948,HS-grad,9,Never-married,Protective-serv,Own-child,White,Male,34095,0,3,United-States,<=50K
6266,18,Self-emp-not-inc,60981,11th,7,Never-married,Other-service,Own-child,White,Female,0,0,4,United-States,<=50K
9820,17,Self-emp-inc,143034,10th,6,Never-married,Other-service,Own-child,White,Male,0,0,4,United-States,<=50K
11021,20,Private,165201,Some-college,10,Never-married,Adm-clerical,Own-child,White,Female,0,0,4,United-States,<=50K
12067,18,?,137363,Some-college,10,Never-married,?,Own-child,White,Female,0,0,4,United-States,<=50K
12971,22,Self-emp-not-inc,279802,Some-college,10,Never-married,Prof-specialty,Own-child,White,Female,0,0,3,United-States,<=50K
13986,20,Private,132053,Some-college,10,Never-married,Prof-specialty,Own-child,White,Female,0,0,2,United-States,<=50K
14202,21,?,163911,Some-college,10,Never-married,?,Own-child,White,Female,0,0,3,United-States,<=50K
17385,21,Private,83580,Some-college,10,Never-married,Prof-specialty,Own-child,Amer-Indian-Eskimo,Female,0,0,4,United-States,<=50K
18243,22,?,31102,Some-college,10,Never-married,?,Own-child,Asian-Pac-Islander,Female,0,0,4,South,<=50K
18835,19,Private,28119,Some-college,10,Never-married,Other-service,Own-child,White,Female,0,0,4,United-States,<=50K
19426,24,Local-gov,176178,Assoc-acdm,12,Never-married,Prof-specialty,Own-child,White,Female,0,0,2,United-States,<=50K
19749,23,Private,72887,HS-grad,9,Never-married,Craft-repair,Own-child,Asian-Pac-Islander,Male,0,0,1,Vietnam,<=50K
21349,18,Private,112974,11th,7,Never-married,Prof-specialty,Other-relative,White,Male,0,0,3,United-States,<=50K
22386,22,?,224238,Some-college,10,Never-married,?,Own-child,White,Male,0,0,2,United-States,<=50K
22927,17,?,332666,10th,6,Never-married,?,Own-child,White,Female,0,0,4,United-States,<=50K
22957,18,Self-emp-not-inc,230373,11th,7,Never-married,Other-service,Own-child,White,Female,594,0,4,United-States,<=50K
22959,21,Private,184135,HS-grad,9,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,1,United-States,<=50K
23216,22,Private,184975,HS-grad,9,Married-spouse-absent,Other-service,Own-child,White,Female,0,0,3,United-States,<=50K
26661,18,Federal-gov,201686,11th,7,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,4,United-States,<=50K
27490,21,Local-gov,309348,Some-college,10,Never-married,Adm-clerical,Not-in-family,White,Female,594,0,4,United-States,<=50K
29473,22,Private,205939,Bachelors,13,Never-married,Exec-managerial,Own-child,White,Male,2202,0,4,United-States,<=50K
29507,18,Private,152044,10th,6,Never-married,Other-service,Own-child,White,Female,0,0,3,United-States,<=50K
30001,18,Private,279593,11th,7,Never-married,Prof-specialty,Own-child,White,Female,0,0,2,United-States,<=50K
30726,21,?,107801,Some-college,10,Never-married,?,Own-child,White,Female,0,0,3,United-States,<=50K
31804,19,Private,237848,Some-college,10,Never-married,Other-service,Own-child,White,Male,0,0,3,United-States,<=50K
32313,18,Never-worked,153663,Some-college,10,Never-married,?,Own-child,White,Male,0,0,4,United-States,<=50K